# Generated by Django 5.2.1 on 2025-07-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('post_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('video', 'Video'), ('reel', 'Reel'), ('live', 'Live')], default='post', max_length=10)),
                ('post_timestamp_dt', models.DateTimeField(null=True)),
                ('post_timestamp_text', models.TextField()),
                ('post_content', models.TextField(blank=True, null=True)),
                ('post_imgs', models.JSONField(blank=True, default=list, null=True)),
                ('watch_count', models.IntegerField(blank=True, null=True)),
                ('reactions', models.JSONField(blank=True, default=dict, null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('content_pillar', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Test Campaign', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommentCampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='PageInfo.facebookpost')),
            ],
        ),
        migrations.CreateModel(
            name='FBCommentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('dashboard_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dashboard_type', models.CharField(choices=[('seeding', 'Seeding'), ('activity', 'Activity')], default='seeding', max_length=50)),
                ('screenshot_path', models.ImageField(blank=True, null=True, upload_to='post_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='PageInfo.commentcampaigngroup')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_url', models.TextField()),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_img_url', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('reaction', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp_text', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('like_status', models.CharField(blank=True, default='ยังไม่ถูกใจ', max_length=50, null=True)),
                ('share_status', models.CharField(blank=True, default='ยังไม่แชร์', max_length=50, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword_group', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PageInfo.fbcommentdashboard')),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('lemon8', 'Lemon8'), ('youtube', 'Youtube')], default='facebook', max_length=20)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.URLField(blank=True, max_length=500, null=True)),
                ('page_username', models.CharField(blank=True, max_length=255, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_business_page', models.BooleanField(blank=True, null=True)),
                ('page_followers', models.CharField(blank=True, max_length=100, null=True)),
                ('page_likes', models.CharField(blank=True, max_length=100, null=True)),
                ('page_followers_count', models.IntegerField(blank=True, null=True)),
                ('page_likes_count', models.CharField(blank=True, max_length=100, null=True)),
                ('page_talking_count', models.CharField(blank=True, max_length=100, null=True)),
                ('page_were_here_count', models.CharField(blank=True, max_length=100, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('page_category', models.CharField(blank=True, max_length=255, null=True)),
                ('page_address', models.CharField(blank=True, max_length=500, null=True)),
                ('page_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('page_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('page_website', models.URLField(blank=True, max_length=500, null=True)),
                ('following_count', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('post_count', models.IntegerField(blank=True, null=True)),
                ('page_join_date', models.CharField(blank=True, max_length=100, null=True)),
                ('page_videos_count', models.BigIntegerField(blank=True, null=True)),
                ('page_total_views', models.BigIntegerField(blank=True, null=True)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='PageInfo.pagegroup')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_followers_count', models.IntegerField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageInfo.pageinfo')),
            ],
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_posts', to='PageInfo.pageinfo'),
        ),
    ]
