# Generated by Django 5.2.1 on 2025-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcomment',
            name='post_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fbcommentdashboard',
            name='post_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
