# Generated by Django 5.2.1 on 2025-06-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0002_alter_facebookcomment_post_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
