# Generated by Django 5.2.1 on 2025-07-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0002_pagegroup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcampaigngroup',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='PageInfo.facebookpost'),
        ),
    ]
