# Generated by Django 5.2.1 on 2025-07-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0003_alter_commentcampaigngroup_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(max_length=500)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('post_imgs', models.URLField(blank=True, null=True)),
                ('post_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('reaction', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('share_count', models.IntegerField(blank=True, null=True)),
                ('save_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_posts', to='PageInfo.pageinfo')),
            ],
        ),
    ]
