# Generated by Django 5.2.1 on 2025-07-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0004_tiktokpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiktokpost',
            old_name='reaction',
            new_name='like_count',
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='platform',
            field=models.CharField(default='tiktok', max_length=20),
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='post_timestamp_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokpost',
            name='post_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
