# Generated by Django 5.2.1 on 2025-06-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0004_alter_facebookcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookcomment',
            name='post_id',
        ),
    ]
