# Generated by Django 5.2.1 on 2025-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0005_remove_facebookcomment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcomment',
            name='profile_img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
