# Generated by Django 5.2.1 on 2025-07-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0005_rename_reaction_tiktokpost_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokpost',
            name='post_imgs',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
