# Generated by Django 5.2.1 on 2025-06-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0006_alter_facebookcomment_profile_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcomment',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PageInfo.fbcommentdashboard'),
        ),
    ]
