# Generated by Django 5.2.1 on 2025-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0007_facebookcomment_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbcommentdashboard',
            name='dashboard_type',
            field=models.CharField(choices=[('seeding', 'Seeding'), ('activity', 'Activity')], default='seeding', max_length=50),
        ),
    ]
