# Generated by Django 5.2.1 on 2025-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0008_fbcommentdashboard_dashboard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcomment',
            name='like_status',
            field=models.CharField(blank=True, default='ยังไม่ถูกใจ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facebookcomment',
            name='share_status',
            field=models.CharField(blank=True, default='ยังไม่แชร์', max_length=50, null=True),
        ),
    ]
