# Generated by Django 5.2.1 on 2025-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0009_facebookcomment_like_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcomment',
            name='comment_type',
            field=models.CharField(choices=[('seeding', 'Seeding'), ('organic', 'Organic')], default='seeding', max_length=50),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('video', 'Video'), ('reel', 'Reel')], default='post', max_length=10),
        ),
    ]
