# Generated by Django 5.2.1 on 2025-07-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0010_facebookcomment_comment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookcomment',
            name='comment_type',
        ),
    ]
