# Generated by Django 5.2.1 on 2025-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0011_remove_facebookcomment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('video', 'Video'), ('reel', 'Reel'), ('live', 'Live')], default='post', max_length=10),
        ),
    ]
