# Generated by Django 5.2.1 on 2025-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0012_alter_facebookpost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='post_timestamp_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
