# Generated by Django 5.2.1 on 2025-07-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0013_alter_facebookpost_post_timestamp_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbcommentdashboard',
            name='post_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_dashboards', to='PageInfo.pagegroup'),
        ),
    ]
