# Generated by Django 5.2.1 on 2025-07-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0014_fbcommentdashboard_post_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fbcommentdashboard',
            name='post_campaign',
        ),
        migrations.AddField(
            model_name='fbcommentdashboard',
            name='campaign_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PageInfo.commentcampaigngroup'),
        ),
    ]
