# Generated by Django 5.2.1 on 2025-07-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0015_commentcampaigngroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbcommentdashboard',
            name='campaign_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='PageInfo.commentcampaigngroup'),
        ),
    ]
