# Generated by Django 5.2.1 on 2025-07-15 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0016_alter_fbcommentdashboard_campaign_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcampaigngroup',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='PageInfo.facebookpost'),
        ),
    ]
