# Generated by Django 5.2.1 on 2025-07-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0017_commentcampaigngroup_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbcommentdashboard',
            name='link_url',
        ),
    ]
